openapi: 3.0.3
info:
  title: EmporioLambda BE
  description: Queste sono le OpenAPI per il microservizio designato alla gestione degli indirizzi
  version: 0.1.0

servers:
# Added by API Auto Mocking Plugin
- description: SwaggerHub API Auto Mocking
  url: https://virtserver.swaggerhub.com/swexception4/OpenAPI/0.1.0/addresses
- description: serverless offline
  url: http://localhost:4000/dev/addresses

paths:
  /addresses:
    $ref: "addresses.yml"
  /addresses/{id}:
    $ref: "addressesByID.yml"